<?php
# Copyright (c) 2016, Laird
# Contact: ews-support@lairdtech.com

	require("webLCM.php");

	$returnedResult = array(
		'SDCERR' => array(
			'SDCERR_SUCCESS' => SDCERR_SUCCESS,
			'SDCERR_FAIL' => SDCERR_FAIL,
			'SDCERR_INVALID_NAME' => SDCERR_INVALID_NAME,
			'SDCERR_INVALID_CONFIG' => SDCERR_INVALID_CONFIG,
			'SDCERR_INVALID_DELETE' => SDCERR_INVALID_DELETE,
			'SDCERR_POWERCYCLE_REQUIRED' => SDCERR_POWERCYCLE_REQUIRED,
			'SDCERR_INVALID_PARAMETER' => SDCERR_INVALID_PARAMETER,
			'SDCERR_INVALID_EAP_TYPE' => SDCERR_INVALID_EAP_TYPE,
			'SDCERR_INVALID_WEP_TYPE' => SDCERR_INVALID_WEP_TYPE,
			'SDCERR_INVALID_FILE' => SDCERR_INVALID_FILE,
			'SDCERR_INSUFFICIENT_MEMORY' => SDCERR_INSUFFICIENT_MEMORY,
			'SDCERR_NOT_IMPLEMENTED' => SDCERR_NOT_IMPLEMENTED,
			'SDCERR_NO_HARDWARE' => SDCERR_NO_HARDWARE,
			'SDCERR_INVALID_VALUE' => SDCERR_INVALID_VALUE,
		),
		'SESSION' => SDCERR_FAIL,
		'IGNORE_SESSION' => SDCERR_FAIL,
		'PLUGINS' => null,
	);
	$iniFile = readINI();
	$returnedResult['DEBUG'] = debugLevel();
	$returnedResult['PLUGINS'] = generatePlugins($iniFile);
	$returnedResult['IGNORE_SESSION'] = skipLogin();
	$returnedResult['SESSION'] = verifyAuthentication(false);
	echo json_encode($returnedResult);

?>
